openapi: 3.0.1
info:
  title: TheDome API
  version: 1.0.0
paths:
  /:
    get:
      summary: Root endpoint
      responses:
        '200':
          description: API information
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  version:
                    type: string
                  docs:
                    type: string
  /servers:
    get:
      summary: List servers
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: false
        - in: query
          name: size
          schema:
            type: integer
          required: false
        - in: query
          name: map
          schema:
            type: string
          required: false
        - in: query
          name: flag
          schema:
            type: string
          required: false
        - in: query
          name: region
          schema:
            type: string
          required: false
        - in: query
          name: difficulty
          schema:
            type: string
          required: false
        - in: query
          name: modded
          schema:
            type: boolean
          required: false
        - in: query
          name: official
          schema:
            type: boolean
          required: false
        - in: query
          name: wipeSchedule
          schema:
            type: string
          required: false
        - in: query
          name: ranking
          schema:
            type: integer
          required: false
        - in: query
          name: playerCount
          schema:
            type: integer
          required: false
        - in: query
          name: groupLimit
          schema:
            type: integer
          required: false
        - in: query
          name: order
          schema:
            type: string
          required: false
        - in: query
          name: name
          schema:
            type: string
          required: false
      responses:
        '200':
          description: List of servers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServersResponse'
  /filters/options:
    get:
      summary: Available filter options
      responses:
        '200':
          description: Filter options
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FiltersOptions'

  /auth/anonymous:
    post:
      summary: Obtain anonymous access token
      responses:
        '200':
          description: Access token and username
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessToken'

  /auth/upgrade:
    post:
      summary: Upgrade anonymous account
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpgradeRequest'
      responses:
        '200':
          description: Authentication tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenPair'
        '409':
          description: Username already exists

  /auth/register:
    post:
      summary: Register user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Authentication tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenPair'
        '409':
          description: Username already exists

  /auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Authentication tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenPair'
        '401':
          description: Invalid credentials

  /auth/google:
    post:
      summary: Login with Google
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoogleAuthRequest'
      responses:
        '200':
          description: Authentication tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenPair'
        '401':
          description: Invalid credentials

  /auth/refresh:
    post:
      summary: Refresh tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: New tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenPair'
        '401':
          description: Invalid refresh token

  /fcm/token:
    post:
      summary: Register FCM token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FcmTokenRequest'
      responses:
        '201':
          description: Token registered

  /fcm/token/{token}:
    delete:
      summary: Delete FCM token
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Token removed

components:
  schemas:
    ServerInfo:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        wipe:
          type: string
          format: date-time
        next_wipe:
          type: string
          format: date-time
        next_map_wipe:
          type: string
          format: date-time
        status:
          type: string
        ranking:
          type: integer
        modded:
          type: boolean
        player_count:
          type: integer
        server_capacity:
          type: integer
        map_name:
          type: string
        cycle:
          type: number
          format: double
        server_flag:
          type: string
        region:
          type: string
        max_group:
          type: integer
        difficulty:
          type: string
        wipe_schedule:
          type: string
        is_official:
          type: boolean
        server_ip:
          type: string
        map_image:
          type: string
        map_url:
          type: string
        header_image:
          type: string
        description:
          type: string
        wipe_type:
          type: string
        blueprints:
          type: boolean
        kits:
          type: boolean
        decay:
          type: number
          format: float
        upkeep:
          type: number
          format: double
        rates:
          type: integer
        seed:
          type: integer
        map_size:
          type: integer
        monuments:
          type: integer
        average_fps:
          type: integer
        pve:
          type: boolean
        website:
          type: string
        is_premium:
          type: boolean
    ServersResponse:
      type: object
      properties:
        page:
          type: integer
        size:
          type: integer
        total_pages:
          type: integer
        total_items:
          type: integer
        servers:
          type: array
          items:
            $ref: '#/components/schemas/ServerInfo'
    FiltersOptions:
      type: object
      properties:
        flags:
          type: array
          items:
            type: string
        max_ranking:
          type: integer
        max_player_count:
          type: integer
        max_group_limit:
          type: integer
        maps:
          type: array
          items:
            type: string
        regions:
          type: array
          items:
            type: string
        difficulty:
          type: array
          items:
            type: string
        wipe_schedules:
          type: array
          items:
            type: string
    RegisterRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    RefreshRequest:
      type: object
      properties:
        refreshToken:
          type: string
    GoogleAuthRequest:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    TokenPair:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        username:
          type: string
        email:
          type: string
        provider:
          type: string
        subscribed:
          type: boolean
    AccessToken:
      type: object
      properties:
        accessToken:
          type: string
        username:
          type: string
    FcmTokenRequest:
      type: object
      properties:
        token:
          type: string
        timestamp:
          type: string
    UpgradeRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
