services:
  kotlin-thedome:
    build:
      context: .
    container_name: kotlin-thedome
    restart: unless-stopped
    init: true
    ports:
      - "8080:8080"  # Expose application HTTP API
    environment:
      # Default MongoDB URI for the app to connect to the mongo service
      MONGODB_URI: mongodb://mongo:27017/thedome
      # FETCH_CRON: "*/10 * * * * *"  # Uncomment and set as needed
      # API_KEY: ""  # Optional, set if you have a RustMaps API key
      # PORT: 8080  # Override if you want a different port
      # JWT_SECRET: secret
      # ALLOWED_ORIGINS: "https://example.com,https://example2.com"  # Set allowed CORS origins in production
      # ANON_RATE_LIMIT: 60  # Requests per minute allowed for anonymous users
      # ANON_REFILL_PERIOD: 60  # Seconds per anonymous rate limit window
    depends_on:
      - mongo
    networks:
      - backend
    # env_file: ./.env  # Uncomment if .env file exists

  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"  # Expose MongoDB for local development
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - backend

volumes:
  mongo-data:
    # MongoDB data persistence

networks:
  backend:
    driver: bridge
